import { Geist, Geist_Mono, Outfit, Ovo } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const outfit = Outfit({
  subsets: ["latin"],weight:["400","500","600","700"]
});

const ovo = Ovo({
  subsets: ["latin"],weight:["400"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Derrick Hsu's Personnal Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Head>
          {/* 設定 viewport，讓頁面縮放至 90% */}
          <meta name="viewport" content="width=device-width, initial-scale=0.9" />
        </Head>
      </head>
      <body className="antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white">
        {children}
      </body>
    </html>
  );
}
